[package]
name = "issue416"
version = "0.1.0"
edition = "2021"

[dependencies]
# 0.6.0 is the latest, 0.3.2 is the latest since the armv7 musl hf patch.
libremarkable = { version = "0.3.2", path = "libremarkable" }

[profile.dev]
lto = "off"

[profile.release]
lto = "fat"
